# Conclusion {-}

The study probes into how factors as travel behavior and perceived travel environment can influence tourists' travel satisfaction on Qinghai-Tibet Pleateau. The single-group SEM analysis conducted in this model peper revealed mixed effects across different pathways. Perceived tourist attraction environment significantly influenced travel satisfaction, while perceived road environment had no notable direct effect. Mediating effects showed that better tourist site conditions led to longer daily travel distances, whereas worse road conditions reduced travel distance. Travel modes exhibited minimal direct effects on satisfaction, with walking positively contributing and car driving by others showing the largest negative impact. Regarding travel behavior, frequency of travel to the Qinghai-Tibet Plateau had a minor positive effect on satisfaction, although insignificant, and daily travel distance showed no direct association.

The innovative highlights of the study would be using SEM modeling to comprehensively incorporate all relevant factors that could impact travel satisfaction. While it focused on the perspectives of tourism traveling instead of work commuting, a travel activity that has been well researched and concentrated on. Meanwhile, the study supplements the vacancy of similar travel behavior related studies conducted on a plateau area, as most focuses on cities of low altitude.

There are also some aspects this article can be further improved: 1) if conducting follow-up survey or new survey projects targeted at travel satisfaction, the more standardized and official survey scale, such as Satisfaction with Travel Scale (STS) by @Ettema2011, could be used; 2) objective and measurable traveling time, distance, and road infrastructure geo-spatial data could be calculated and added into this study, however, it is true that such data might not be easy to obtain due to harsh natural environments and governments' privacy concerns; 3) Could further dig into the dynamic intersecting influences between variables by performing multiple-group models using variables such as residence, profession, or travel modes.




